<header role="banner">
    
    <button type="button" class="drawer-toggle drawer-hamburger">
      <span class="sr-only">toggle navigation</span>
      <span class="drawer-hamburger-icon"></span>
    </button>

    <nav class="drawer-nav" role="navigation">
      <ul class="drawer-menu">
        <li><a class="drawer-brand" href="/">Main</a></li>
        <li><a class="drawer-menu-item" href="./profiles">Profiles</a></li>
        <li><a class="drawer-menu-item" href="./newProfile">Create Profile</a></li>
        <li><a class="drawer-menu-item" href="./loops">Loops</a></li>
      </ul>
    </nav>
  </header>